### ISSUE TITLE
Cannot select on top of WebGL canvas

### ISSUE THREAD

**Issue by unknownMarty** [casavi/react-region-select#12]
HI thanks for the lib!

I'm currently using your lib for drawing on top of https://github.com/uber/react-map-gl. Somehow I cannot get your div on top of the map. Does it support WebGL canvas?

**Comment by davidlanger** [comment]
I never used it for this use case. You might have success with changing z-indexes. Happy for pull requests.

**Comment by d0b1010r** [comment]
Closing - still happy for pull requests that fix it
