### ISSUE TITLE
Can I select multiple items using one region?

### ISSUE THREAD

**Issue by hajdun** [casavi/react-region-select#14]
Can I select multiple items using one region? 
If yes, is there a suggested implementation? I need to select images below the region.
Thank you!

**Comment by d0b1010r** [comment]
Hi hajdun, there currently is no concept of items: it’s just one or more rectangles that you select with your mouse. These are just x/y/width/height. There can be more than one selection. But what’s below those selections is up to you. In our case it‘s an image as a background

**Comment by d0b1010r** [comment]
Closing - no response.
