### ISSUE TITLE
regionStyle prop does not work

### ISSUE THREAD

**Issue by jnicoleoliveira** [casavi/react-region-select#9]
Hi,
I'm currently trying to adjust the region styling using the regionStyle prop. Am I wrong to assume this prop exists, or is it just not working for me?

Thank you!

```
RegionSelect maxRegions={1}
             regions={this.state.regions}
             onChange={this.handleRegionsChange}
             className={styles.heatmapSelect} 
             regionStyle={{background: "blue"}}
>
             {this.renderHeatmap()}
             {this.renderHighlightedPoints()}
</RegionSelect>
```

**Comment by jnicoleoliveira** [comment]
Oh. Actually I just realized the code was in a PR... and not merged in yet. ☹️

**Comment by davidlanger** [comment]
Yeah I’m currently don’t have that much time to look into the repo and merge PRs. Sorry for that! Will try to work on that in the coming days.

**Comment by jnicoleoliveira** [comment]
That would be great - I would love to use it. Thanks!

**Comment by davidlanger** [comment]
Merged
